name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
   - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: |
        docker buildx build --file Dockerfile --tag ghcr.io/arnaud-feldmann/http_exercice:${{ steps.date.outputs.date }} --tag ghcr.io/arnaud-feldmann/http_exercice:latest --platform linux/arm64,linux/amd64 .
        docker push ghcr.io/arnaud-feldmann/http_exercice --all-tags
